name: PxWeb2_Build

on:
  workflow_dispatch:    # manual trigger from GitHub UI
  #push:
  #  branches: [ main ]  # optional: build on pushes to main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v5        
      with:
        repository: PxTools/PxWeb2
        ref: "v2.4.0"        

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build    
    
    - name: Print current folder path with PowerShell
      shell: pwsh
      run: |
          Write-Output "Current folder path is: $PWD"          
          Write-Output "Content get-childitem -path $PWD"
          #get-childitem -path $PWD -recurse
          get-childitem -path "packages\pxweb2\dist"
          
    #- name: Zip deployable package
    #  shell: pwsh
    #  run: |        
    #    Compress-Archive -Path "artifacts\pxweb\_PublishedWebsites\*" -DestinationPath "PxWeb_Release.zip"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PxWeb_Release
        #path: PxWeb_Release.zip
        path: packages\pxweb2\dist
        if-no-files-found: error
