name: PxWeb_Build

on:
  workflow_dispatch:    # manual trigger from GitHub UI
  #push:
  #  branches: [ main ]  # optional: build on pushes to main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v5        
      with:
        repository: statisticssweden/PxWeb
        ref: "2025.v1"
        submodules: true        

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Install cloc
      run: |
        choco install cloc -y  # Windows
         # or: sudo apt-get install cloc -y  # Linux

    - name: Count lines of code
      run: cloc . --exclude-dir=bin,obj,node_modules

    - name: Download SonarScanner for MSBuild 
      run: | 
        dotnet tool install --global dotnet-sonarscanner
    
    - name: SonarCloud - Begin 
      shell: pwsh
      run: >      
        dotnet-sonarscanner begin
        /k:"${{ secrets.SONAR_PROJECT1 }}"
        /o:"${{ secrets.SONAR_ORG }}"
        /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        /d:sonar.host.url="https://sonarcloud.io"

    - name: Restore packages
      run: nuget restore PCAxis.PX-Web.sln

    - name: Build the application      
      #run: msbuild PCAxis.PX-Web.sln /t:Build /p:Configuration=Release /p:OutputPath=${{ github.workspace }}\artifacts\PxWeb # works
      run: msbuild PCAxis.PX-Web.sln /t:Build /p:Configuration=Release 
      #run: msbuild PCAxis.PX-Web.sln /p:Configuration=Release /p:WebPublishMethod=FileSystem /p:PublishUrl=artifacts\PxWeb /t:WebPublish #failed
      #run: msbuild PXWeb\PXWeb.csproj /p:Configuration=Release /p:WebPublishMethod=FileSystem /p:PublishUrl=artifacts\PxWeb /t:WebPublish  /p:PreBuildEvent=false #failed
      #run: msbuild PXWeb\PXWeb.csproj /t:Build /p:Configuration=Release /p:OutputPath=${{ github.workspace }}\artifacts\PxWeb

    - name: Build the application publishweb           
      run: msbuild PXWeb\PXWeb.csproj /p:Configuration=Release /p:WebPublishMethod=FileSystem /p:PublishUrl=artifacts\PxWeb /t:WebPublish  /p:SolutionDir="${{ github.workspace }}\"

    - name: Generate SBOM with Anchore 
      uses: anchore/sbom-action@v0.17.0
      with: 
        path: . 
        format: cyclonedx-json 
        output-file: sbom_pxweb.json
        args: "--name Pxweb --version 1.1.0"
        

    - name: Upload SBOM artifact 
      uses: actions/upload-artifact@v4
      with: 
        name: sbom_pxweb
        path: sbom_pxweb.json

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate CycloneDX SBOM
      run: |
        syft . --output cyclonedx-json=sbom_pxweb2.json --source-name Pxweb --source-version 1.1.0

    - name: Upload SBOM artifact 2
      uses: actions/upload-artifact@v4
      with: 
        name: sbom_pxweb2
        path: sbom_pxweb2.json
        
    - name: create upack 
      run: | 
        New-Item -ItemType Directory -Path package\content -Force        
        Copy-Item -Path artifacts\pxweb\* -Destination package\content\ -Recurse
        copy-item -path sbom_pxweb.json -destination package\        
        $json = @{
            name= "Pxweb"
            version= "1.0.0"
            description= "Test universal package"
            authors= @("GitHub Actions")
            } |convertto-json -depth 5
         $json | Out-File -FilePath package\upack.json -Encoding utf8

    - name: Zip into .upack 
      run: | 
        Compress-Archive -Path package\* -DestinationPath pxweb-1.0.0.upack        
        ls 
    
    - name: Print current folder path with PowerShell
      shell: pwsh
      run: |
          Write-Output "Current folder path is: $PWD"          

    - name: SonarCloud - End 
      run: | 
        dotnet-sonarscanner end ` /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PxWeb_Release
        #path: PxWeb_Release.zip
        #path: artifacts/pxweb/_PublishedWebsites
        path: artifacts/pxweb
        if-no-files-found: error

  
    - name: Upload upack
      uses: actions/upload-artifact@v4
      with:
        name: PxWeb_upack
        #path: PxWeb_Release.zip
        path: pxweb-1.0.0.upack
        if-no-files-found: error
