name: PxWebApi_Build

on:
  workflow_dispatch:    # manual trigger from GitHub UI
  #push:
  #  branches: [ main ]  # optional: build on pushes to main

env:
  PXWEB2_VERSION: "v2.1.1" 

jobs:
  build:
    name: Building for ${{ matrix.label }}
    runs-on: windows-latest
    strategy:
      matrix:
        include: 
          - arch: win-x64 
            label: "Windows 64â€‘bit"
    
    steps:
    - name: Debug information
      run: |
        echo "PXWEB2_VERSION: $PXWEB2_VERSION"
        
    - name: Checkout source
      uses: actions/checkout@v6        
      with:
        repository: PxTools/PxWebApi
        ref: ${{ env.PXWEB2_VERSION }}       

    - name: Setup .NET
      uses: actions/setup-dotnet@v5      
      with:
        global-json-file: "./global.json"

    - name: Restore dependencies
      run: dotnet restore --runtime ${{ matrix.arch }}

    - name: Format code
      run: dotnet format --severity error --no-restore --verify-no-changes --verbosity normal

    - name: Build the application
      run: dotnet build --no-restore --runtime ${{ matrix.arch }} PxWeb/PxWeb.csproj

    - name: Publish the application
      run: dotnet publish --runtime ${{ matrix.arch }} --output ./release PxWeb/PxWeb.csproj    
    
    - name: Zip deployable package
      shell: pwsh
      run: |        
        Compress-Archive -Path "release\wwwroot\Database\*" -DestinationPath "PxWebapi_${{ env.PXWEB2_VERSION }}.zip"
        
    - name: Print current folder path with PowerShell
      shell: pwsh
      run: |
          Write-Output "Current folder path is: $PWD"                    
          get-childitem -path $PWD -#recurse
          #get-childitem -path "./release"
                
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PxWebapi_${{ env.PXWEB2_VERSION }}
        path: PxWebapi_${{ env.PXWEB2_VERSION }}.zip        
        if-no-files-found: error
