name: PxWeb_Build

on:
  workflow_dispatch:    # manual trigger from GitHub UI
  #push:
  #  branches: [ main ]  # optional: build on pushes to main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v5        
      with:
        repository: statisticssweden/PxWeb
        ref: "2025.v1"
        submodules: true        

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Install cloc
      run: |
        choco install cloc -y  # Windows
         # or: sudo apt-get install cloc -y  # Linux

    - name: Count lines of code
      run: cloc . --exclude-dir=bin,obj,node_modules

    - name: Download SonarScanner for MSBuild 
      run: | 
        dotnet tool install --global dotnet-sonarscanner
    
    - name: SonarCloud - Begin 
      shell: pwsh
      run: >      
        dotnet-sonarscanner begin
        /k:"${{ secrets.SONAR_PROJECT1 }}"
        /o:"${{ secrets.SONAR_ORG }}"
        /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        /d:sonar.host.url="https://sonarcloud.io"

    - name: Restore packages
      run: nuget restore PCAxis.PX-Web.sln

    - name: Build the application      
      run: msbuild PCAxis.PX-Web.sln /t:Build /p:Configuration=Release /p:OutputPath=${{ github.workspace }}\artifacts\PxWeb
      #run: msbuild PXWeb\PXWeb.csproj /t:Build /p:Configuration=Release /p:OutputPath=${{ github.workspace }}\artifacts\PxWeb

    - name: Print current folder path with PowerShell
      shell: pwsh
      run: |
          Write-Output "Current folder path is: $PWD"          

    - name: SonarCloud - End 
      run: | 
        dotnet-sonarscanner end ` /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PxWeb_Release
        #path: PxWeb_Release.zip
        path: artifacts/pxweb/_PublishedWebsites
        if-no-files-found: error
